name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core: ^2.11.0
  firebase_database: ^10.1.2
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
