// Autogenerated from Pigeon (v16.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, PigeonValueSource) {
  /// The value was defined by a static constant.
  PigeonValueSourceValueStatic = 0,
  /// The value was defined by default config.
  PigeonValueSourceValueDefault = 1,
  /// The value was defined by fetched config.
  PigeonValueSourceValueRemote = 2,
};

/// Wrapper for PigeonValueSource to allow for nullability.
@interface PigeonValueSourceBox : NSObject
@property(nonatomic, assign) PigeonValueSource value;
- (instancetype)initWithValue:(PigeonValueSource)value;
@end


/// The codec used by RemoteConfigHostApi.
NSObject<FlutterMessageCodec> *RemoteConfigHostApiGetCodec(void);

@protocol RemoteConfigHostApi
- (void)ensureInitializedAppName:(NSString *)appName completion:(void (^)(FlutterError *_Nullable))completion;
- (void)activateAppName:(NSString *)appName completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)fetchAppName:(NSString *)appName completion:(void (^)(FlutterError *_Nullable))completion;
- (void)fetchAndActivateAppName:(NSString *)appName completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)setConfigSettingsAppName:(NSString *)appName fetchTimeout:(NSInteger)fetchTimeout minimumFetchInterval:(NSInteger)minimumFetchInterval completion:(void (^)(FlutterError *_Nullable))completion;
- (void)setDefaultsAppName:(NSString *)appName defaultParameters:(NSDictionary<NSString *, id> *)defaultParameters completion:(void (^)(FlutterError *_Nullable))completion;
- (void)getAllAppName:(NSString *)appName completion:(void (^)(NSDictionary<id, id> *_Nullable, FlutterError *_Nullable))completion;
- (void)getPropertiesAppName:(NSString *)appName completion:(void (^)(NSDictionary<id, id> *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpRemoteConfigHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<RemoteConfigHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
