name: cloud_firestore_odm_generator_integration_test
version: 1.0.0-dev.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.6.0
  cloud_firestore_odm: ^1.0.0-dev.57
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.0
  cloud_firestore_odm_generator: ^1.0.0-dev.57
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: '>=6.6.1 <7.0.0'

flutter:
  uses-material-design: false
