name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  firebase_in_app_messaging: ^0.7.1+1
  firebase_in_app_messaging_platform_interface: ^0.2.2+1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
