name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_analytics: ^10.3.0
  firebase_core: ^2.11.0
  firebase_in_app_messaging: ^0.7.2
  firebase_in_app_messaging_platform_interface: ^0.2.3
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
