name: firebase_vertexai
description: "Firebase Vertex AI SDK."
version: 0.1.0
homepage: https://firebase.google.com/docs/vertex-ai/get-started?platform=flutter

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  firebase_app_check: ^0.2.1+16
  firebase_core: ^2.26.0
  firebase_core_platform_interface: ^5.0.0
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3
