name: firebase_performance_web
description: Web implementation of Firebase Performance monitoring.
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_performance/firebase_performance_web
version: 0.1.3

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  _flutterfire_internals: ^1.2.0
  firebase_core: ^2.11.0
  firebase_core_web: ^2.4.0
  firebase_performance_platform_interface: ^0.1.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebasePerformanceWeb
        fileName: firebase_performance_web.dart
